# Credit Card Fraud Prediction models

In [18]:
# importing everything we will be using 

%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#pd.set_option("display.max_rows", None)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.utils import resample

import warnings
warnings.filterwarnings('ignore')

In [19]:
#importing data

data = pd.read_csv('User0_credit_card_transactions copie.csv')

## Data description

In [20]:
data.head()

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No

In [21]:
data.shape

(19963, 15)

In [22]:
data.columns

Index(['User', 'Card', 'Year', 'Month', 'Day', 'Time', 'Amount', 'Use Chip',
       'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC',
       'Errors?', 'Is Fraud?'],
      dtype='object')

In [23]:
data.describe()

,User,Card,Year,Month,Day,Merchant Name,Zip,MCC
count,19963.0,19963.000000,19963.000000,19963.000000,19963.000000,1.996300e+04,18316.000000,19963.000000
mean,0.0,1.910735,2011.011922,6.568101,15.743876,7.825653e+17,88812.744922,5617.940239
std,0.0,1.237763,5.048146,3.477497,8.801378,4.040602e+18,13711.491085,707.982901
min,0.0,0.000000,2002.000000,1.000000,1.000000,-9.179793e+18,1012.000000,1711.000000
25%,0.0,0.000000,2007.000000,4.000000,8.000000,-1.288082e+18,91750.000000,5311.000000
50%,0.0,2.000000,2011.000000,7.000000,16.000000,8.384250e+17,91750.000000,5499.000000
75%,0.0,3.000000,2015.000000,10.000000,23.000000,4.060647e+18,91752.000000,5912.000000
max,0.0,4.000000,2020.000000,12.000000,31.000000,9.137769e+18,99504.000000,9402.000000

In [24]:
data.dtypes

User                int64
Card                int64
Year                int64
Month               int64
Day                 int64
Time               object
Amount             object
Use Chip           object
Merchant Name       int64
Merchant City      object
Merchant State     object
Zip               float64
MCC                 int64
Errors?            object
Is Fraud?          object
dtype: object

## DATA CLEANING

In [27]:
#data.duplicated().sum()##
#data.drop_duplicates() # checking and dropping duplicates 

# NO DUPLICATES

In [28]:
# droping the column User because it has too many unique values,the User column had no unique values 
# User is just an index not an ID 

data.drop(['User'], axis=1, inplace=True)

In [29]:
# check for NaN values 
data.isna().sum()

Card                  0
Year                  0
Month                 0
Day                   0
Time                  0
Amount                0
Use Chip              0
Merchant Name         0
Merchant City         0
Merchant State     1317
Zip                1647
MCC                   0
Errors?           19389
Is Fraud?             0
dtype: int64

In [31]:
# add Year, Month , Day to one column Called Date
data['Date'] = pd.to_datetime(data[['Year', 'Month', 'Day']])
data['Date'] = data['Date'].dt.strftime('%Y-%m-%d')
# change the data type of the Date column to object
data['Date'] = data['Date'].astype('object')

#Drop year and day, leave month for analysis 

data.drop(['Year','Day'], axis=1, inplace=True) #keep months

In [32]:
# create a list of column names in the desired order
column_order = ['Card', 'Date','Month', 'Time', 'Amount', 'Use Chip', 'Merchant Name',
           'Merchant City', 'Merchant State', 'Zip', 'MCC', 'Errors?', 'Is Fraud?']

# reorder the columns in the DataFrame
data = data[column_order]

### Column Time

In [33]:
#Add column Morning or Night
# Check which Time most frauds accured, morning or night ? 

data['Time'].min()
data['Time'].max()
# create of function to classify time to morning and night
import datetime
def classify_time(time_str):
    time_obj = pd.to_datetime(time_str).time()
    if time_obj >= datetime.time(6, 0) and time_obj <= datetime.time(11, 59):
        return "morning"
    else:
        return "night"
    
data["Time Period"] = data["Time"].apply(classify_time)

### Column amount

In [34]:
## clean column Amount, remove the $ sign 
data['Amount'] = data['Amount'].str.replace('$', '').astype(float).round(0)

In [35]:
## Check the limit, where most frauds accured, more than X number

### Cleaning Merchant city : add column to type of transaction ( online or in-person )

In [36]:
# create a function to categorize merchant type to online and in-person
def categorize_merchant(city):
    if city == 'ONLINE':
        return 'online'
    else:
        return 'in-person'

# Apply the categorize_city function to the 'Merchant City' column
data['Merchant Type'] = data['Merchant City'].apply(categorize_merchant)

In [40]:
## Check relation with Fraud too

### Column Merchant City

In [41]:
data['Merchant State'].value_counts(dropna=False)

CA                    17029
NaN                    1317
NJ                      186
TX                      156
Mexico                  146
MI                      125
NV                      112
NY                       95
IL                       82
FL                       77
IA                       75
MA                       58
WA                       49
Jamaica                  46
Philippines              46
UT                       33
GA                       32
Italy                    32
HI                       31
SC                       27
AK                       24
MO                       23
China                    18
MN                       16
PA                       14
Estonia                  13
AR                       13
Japan                    12
CT                       10
WI                        9
VA                        9
OH                        9
NE                        8
AZ                        7
Portugal                  6
Switzerland               5
Dominican Republic        4
CO                        3
NM                        3
Canada                    2
OR                        1
Name: Merchant State, dtype: int64

In [42]:
## NaN values = 1317, same number as online merchant type. Check if true or not.

### Dealing with MCC Column

In [43]:
# MCC presents the Merchant category code, from this table : 
#https://www.checkout.com/docs/resources/codes/merchant-category-codes
# we see that each number presents a category name, below I will create a new column

In [44]:
## Extracted MCC from Values counts 
# MCC = '5411','5912','5300','5541','5311','5812','5499','5942','7538','4900','5814','4814','5310','4829','5815','7230','5211','7832','4899','5651','7349','4722','5193','5813','5719','6300','3722','5970','3684','7011','7210','3509','7542','5251','5921','3596','3780','3730','3640','3504','3775','5655','3389','3390','8043','8021','3359','3387','3395','7996','4214','8099','3771','9402','5621','3000','3405','8011','3393','7995','5712','3256','3001','5661','3058','4131','4121','4511','3066','3132','5094','8041','5732','5932','8111','3174','7802','3260','1711','4112','7801','7531','5733','5533','8049','3007','3008','3006','7922','5816','4411','7549','5947','3009'

In [45]:
# MCC description mapping
mcc_description = {
     1711: "Air Conditioning Contractors – Sales and Installation, Heating Contractors – Sales, Service, Installation",
    3000: "UNITED AIRLINES",
    3001: "AMERICAN AIRLINES",
    3006: "JAPAN AIRLINES",
    3007: "AIR FRANCE",
    3008: "LUFTHANSA",
    3009: "AIR CANADA",
    3058: "DELTA",
    3066: "SOUTHWEST",
    3132: "Airlines",
    3174: "Airlines",
    3256: "ALASKA AIRLINES",
    3260: "Airlines",
    3359: "PAYLESS CAR RENTAL",
    3387: "ALAMO RENT-A-CAR",
    3389: "AVIS RENT-A-CAR",
    3390: "DOLLAR RENT-A-CAR",
    3393: "NATIONAL CAR RENTAL",
    3395: "THRIFTY RENT-A-CAR",
    3405: "ENTERPRISE RENT-A-CAR",
    3504: "HILTON HOTELS",
    3509: "MARRIOTT HOTELS",
    3596: "Hotels/Motels/Inns/Resorts",
    3640: "HYATT HOTEL",
    3684: "BUDGET HOST INNS",
    3722: "WYNDHAM HOTEL AND RESORTS",
    3730: "MGM GRAND HOTEL",
    3771: "Hotels/Motels/Inns/Resorts",
    3775: "Hotels/Motels/Inns/Resorts",
    3780: "Hotels/Motels/Inns/Resorts",
    4112: "Passenger Railways",
    4121: "Taxicabs and Limousines",
    4131: "Bus Lines, Including Charters, Tour Buses",
    4214: "Motor Freight Carriers, Moving and Storage Companies, Trucking – Local/Long Distance, Delivery Services – Local",
    4411: "Cruise and Steamship Lines",
    4511: "Airlines, Air Carriers (not listed elsewhere)",
    4722: "Travel Agencies and Tour Operations",
    4814: "Fax services, Telecommunication Services",
    4829: "Money Orders – Wire Transfer",
    4899: "Cable and other pay television (previously Cable Services)",
    4900: "Electric, Gas, Sanitary and Water Utilities",
    5094: "Precious Stones and Metals, Watches and Jewelry",
    5193: "Florists’ Supplies, Nursery Stock and Flowers",
    5211: "Lumber and Building Materials Stores",
    5251: "Hardware Stores",
    5300: "Wholesale Clubs",
    5310: "Discount Stores",
    5311: "Department Stores",
    5411: "Grocery Stores, Supermarkets",
    5499: "Misc. Food Stores – Convenience Stores and Specialty Markets",
    5533: "Automotive Parts, Accessories Stores",
    5541: "Service Stations (with or without ancillary services)",
    5621: "Women’s Ready-to-Wear Stores",
    5651: "Family Clothing Stores",
    5655: "Sports Apparel, Riding Apparel Stores",
    5661: "Shoe Stores",
    5712: "Furniture, Home Furnishings, and Equipment Stores, Except Appliances",
    5719: "Miscellaneous Home Furnishing Specialty Stores",
    5732: "Electronic Sales",
    5733: "Music Stores, Musical Instruments, Piano Sheet Music",
    5812: "Eating places and Restaurants",
    5813: "Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques",
    5814: "Fast Food Restaurants",
    5815: "Digital Goods: Media, Books, Movies, Music",
    5816: "Digital Goods: Games",
    5912: "Drug Stores and Pharmacies",
    5921: "Package Stores – Beer, Wine, and Liquor",
    5932: "Antique Shops",
    5942: "Book Stores",
    5947: "Card Shops, Gift, Novelty, and Souvenir Shops",
    5970: "Artist’s Supply and Craft Shops",
    6300: "Insurance Sales, Underwriting, and Premiums",
    7011: "Lodging – Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)",
    7210: "Laundry, Cleaning, and Garment Services",
    7230: "Barber and Beauty Shops",
    7349: "Cleaning and Maintenance, Janitorial Services",
    7531: "Automotive Body Repair Shops",
    7538: "Automotive Service Shops",
    7542: "Car Washes",
    7549: "Towing Services",
    7801: "Government-Licensed On-Line Casinos (On-Line Gambling)",
    7802: "Government-Licensed Horse/Dog Racing",
    7832: "Motion Picture Theaters",
    7922: "Theatrical Producers (Except Motion Pictures), Ticket Agencies",
    7995: "Betting (including Lottery Tickets, Casino Gaming Chips, Off-track Betting and Wagers at Race Tracks)",
    7996: "Amusement Parks, Carnivals, Circuses, Fortune Tellers",
    8011: "Doctors and Physicians (Not Elsewhere Classified)",
    8021: "Dentists and Orthodontists",
    8041: "Chiropractors",
    8043: "Opticians, Opticians Goods and Eyeglasses",
    8049: "Podiatrists and Chiropodists",
    8099: "Medical Services and Health Practitioners (Not Elsewhere Classified)",
    8111: "Legal Services and Attorneys",
    9402: "Postal Services – Government Only"
}

# Replace the MCC codes with their descriptions
data['MCC Type'] = data['MCC'].map(mcc_description)

In [47]:
# create a list of column names in the desired order
column_order = ['Card', 'Date','Month', 'Time','Time Period', 'Amount', 'Use Chip', 'Merchant Name',
           'Merchant City','Merchant Type', 'Merchant State', 'Zip', 'MCC','MCC Type','Errors?', 'Is Fraud?']

# reorder the columns in the DataFrame
data = data[column_order]

In [49]:
data.head()

,Card,Date,Month,Time,Time Period,Amount,Use Chip,Merchant Name,Merchant City,Merchant Type,Merchant State,Zip,MCC,MCC Type,Errors?,Is Fraud?
0,0,2002-09-01,9,06:21,morning,134.0,Swipe Transaction,3527213246127876953,La Verne,in-person,CA,91750.0,5300,Wholesale Clubs,NaN,No
1,0,2002-09-01,9,06:42,morning,38.0,Swipe Transaction,-727612092139916043,Monterey Park,in-person,CA,91754.0,5411,"Grocery Stores, Supermarkets",NaN,No
2,0,2002-09-02,9,06:22,morning,120.0,Swipe Transaction,-727612092139916043,Monterey Park,in-person,CA,91754.0,5411,"Grocery Stores, Supermarkets",NaN,No
3,0,2002-09-02,9,17:45,night,129.0,Swipe Transaction,3414527459579106770,Monterey Park,in-person,CA,91754.0,5651,Family Clothing Stores,NaN,No
4,0,2002-09-03,9,06:23,morning,105.0,Swipe Transaction,5817218446178736267,La Verne,in-person,CA,91750.0,5912,Drug Stores and Pharmacies,NaN,No

In [53]:
data['Merchant Name'].value_counts()

-727612092139916043     1759
 4060646732831064559    1723
 5817218446178736267    1642
 2027553650310142703    1601
-34551508091458520      1542
 1913477460590765860     986
 3527213246127876953     898
-5475680618560174533     873
-1288082279022882052     687
-245178307025547046      681
-4500542936415012428     422
-5023497618971072366     383
-1605794445852049456     361
 7945328079774550558     304
 838425044734233142      281
-3345936507911876459     252
 4055257078481058705     249
-4282466774399734331     227
-9092677072201095172     223
 4241336128694185533     218
 3952145593743244256     217
-7421093378627544099     177
-86825621511712373       161
 6666504894937430109     145
 7035602569409149834     126
 8080934608468946743     116
 1878448597312197393     100
 3189517333335617109      91
-521141999023077663       88
 6661973303171003879      82
-6733168469687845480      67
-3220758452254689706      66
 1799189980464955940      66
-3265671264153192329      66
 6455213054093379528      61
-5904116920141006298      61
-2042049018365856408      60
-8129520121141002186      59
 97032797689821735        58
 1715299929786123066      52
-7146670748125200898      50
-5413376491460213491      48
 4751695835751691036      48
-7807051024009846392      47
 3414527459579106770      45
 9137769173591184401      43
-7232193519160172381      42
-112121233619748226       42
 6130287678940178238      40
 5445101915276107289      40
-5162038175624867091      38
-303858256154265716       36
 4552887027432897467      35
-2474135582844411583      33
-1007477596717646975      33
 1270471339275628505      31
 5205099864768539121      31
-5467922351692495955      31
 7501849281341469857      31
-4334232547381218591      31
-4241409341442030551      30
 483490033258680568       30
-8566951830324093739      30
-2744911404133435018      28
-811651038065591449       28
 4722913068560264812      28
 356025483272339731       27
 5237739159769445856      26
 5805127065224074672      26
 8149422946776550490      25
-6161792371494728879      24
-8338381919281017248      23
-8135850083113399757      23
-6406662083475903219      23
-8978688709093014088      22
-5358926309452434861      22
 1108327803852946055      22
 190253443608377572       21
 6654290286221782850      21
-5149532407043754225      21
-1612219785829480227      19
 7069584154815291371      18
 7834055923142137930      18
-6796080605569913348      18
-4752064311331295725      18
 333722291367506728       18
-5581123930363301609      17
 3694722044710185708      17
-2392212127717286832      17
 6135208568923449408      16
-2839510796998857114      16
-7852140307718416782      16
-1908131910424232363      16
-3289339997738008669      15
 9028663324627689893      15
 3991321433720498482      14
 1839636615252322303      14
 7272219750676920057      14
-1046622217034093949      14
-794809796539996541       14
 3129259766334579731      13
-6380232772327219248      13
 9057735476014445185      13
-3360331473322174717      13
 2743403607688382462      12
 308446962162110756       12
 1704172588052121931      12
-7682041491343894633      11
-4956618006720593695      11
-6738340320657348028      11
 6042526206085641250      11
 170491238251862552       10
 2021711124810092453      10
-6571010470072147219      10
 8528733969764750207      10
 3639123430068731390       9
-3796620483240753238       9
-8194607650924472520       9
 1532660746587553006       9
 8919682822789039434       8
 4029529561989901847       8
-962082848414704514        8
-2187837027406294082       8
 8169568748934000044       8
-984444807771159720        8
 5420807550745338570       7
-8826348804033622422       7
 6698459923198770712       7
 5427095414889712052       7
-2472481739355111587       7
 792585973704216220        7
 8052372811390502404       7
 5474320255037684877       7
-3693650930986299431       7
 8438446124682714015       6
 6091778774361517457       6
-8623996359831810778       6
-4534603528863745258       6
 7911967984720722416       6
-8112988161765547736       6
-2714925975323314171       6
-6154654009609542161       6
-5563027962555087834       6
-7153681666062331471       6
-8870050744400617541       6
 1325201427189385167       6
 6515854639642454768       6
-6035332392926029059       5
 6281014248896736213       5
 9080290826242216515       5
 2432259535987809880       5
 3955078056232420067       5
 6882551472640459815       5
-7149657889717994790       5
 4319011153593601999       5
-85070450838390220         5
 7522433618679272954       5
-4530600671233798827       5
-4051610135453927412       5
-5407432205658328113       5
 2091682703301970293       5
-7926496603095741728       5
 208649686760524778        5
-38327192698602251         5
-558490004391330221        4
-5291192879529992085       4
-7052069146128772826       4
 5496837453391316207       4
-1096718711148016337       4
-1642303950890406395       4
 6186818249657280335       4
-8408860211649002936       4
 969539244598959907        4
-3158720288100679142       4
 815048164705147981        4
-886027770047724904        4
 7823310339568339862       4
 8015937620392163821       4
-2646423167124001708       4
-8003206893077088175       4
 2122301195314255670       4
-2565173608660320061       4
 4859277610485539338       4
-6180066865054539496       4
 3452760747765970571       4
 1139640404793641563       4
 8181289561763813437       4
 7994926652245116835       4
-4927381308738947637       4
-3394303430736305494       4
 8085192491360705856       4
 4168533264539032113       4
 2488262616076920733       4
-4184897818455474094       3
-6160036380778658394       3
 564235470684140432        3
-2229125204354103522       3
-4123207960932004856       3
-5095428811101387162       3
 6580488852321097680       3
-2409348358081844536       3
 7348633117201217630       3
 1287592349408969579       3
-2045560830512979632       3
-5407138151142847632       3
 3206274372236068246       3
-8733402887366759764       3
 5641259852281946914       3
-5693635707082433953       3
 7800381288262166718       3
-2917267394248886681       3
 1917517617315869134       3
 8321233717485618931       3
 8860779126936896686       3
-4733023138943446282       3
-4080114895006189502       3
-1747421737252033553       3
-7893972512267186133       3
-4262153608104899730       3
 4396692637427695044       3
 8817183585285780534       3
-1919083664993855228       3
 4872340518840476610       3
-8756901308592001764       3
 4581048999108455719       3
 8431730853983936426       3
 3637940915881900550       3
 1046798872819448119       3
 1674961158980955125       3
 8099188931555596779       3
 486979357790570231        3
 3900920090343001383       3
 5153124891222632189       3
 561686012023964665        3
-5624843686576836279       3
-4405963029101957776       3
 1249837646840206340       3
 6998358937427405121       3
-3739862438923451178       3
-3974456808785049548       3
 7897619913440547617       3
-6445689545366794903       3
-1548743109648102646       3
-2241979537006931381       3
 6237414669820043474       2
 6153239959911234392       2
-5242023790457253191       2
 4203714214008077681       2
-5401953891366957779       2
-5459512864675088320       2
-6126577643733393276       2
 2651933066841159470       2
 4220239106579691834       2
 4557345853589878929       2
-262836971089173986        2
-3735518998732944464       2
 870450682116565133        2
-1100383791597900693       2
-340037481832949048        2
 6099634831216752724       2
 2593569215859721698       2
 7561720987170851043       2
 5768809839176244909       2
 8411251493655171809       2
-5071048630191437902       2
 4888074371193873697       2
 1463851782358267155       2
-6693141325817887208       2
-3395538998277081094       2
 5439543441580637302       2
 7696479762116293950       2
 4796006601552743675       2
-3645834946962336469       2
-7353042200409852611       2
 6181510752141427450       2
-654906551560485216        2
-7132489176515416501       2
-2712614255273971272       2
 7318338187863890922       2
 7955835412544002204       2
-5150361018903504342       2
-6468851116023036091       2
 4183561685194795811       2
-4268682970074714613       2
-3300622673637614440       2
 8245762104511734345       2
 3840644809732378689       2
 1727959631190852231       2
 2418380343376098757       2
-6596282443056447604       2
 4081535247279879452       2
-4191425613099110081       2
-6761066196029841443       2
-4735945406103085164       2
-8919758470918116834       2
-3650057525483423997       2
 5770707555788308209       2
 5488842789313916278       2
-1368157445706054090       2
-7351013489362006275       2
 1670884829620747872       2
-4693979874497918566       2
-5316370718817160874       2
 6286510461983341900       2
 8793545055147237096       2
 2726816108624204598       2
 6098687587141770242       2
 8947800840411535776       2
 4645744106416199425       2
-3086825409791490122       2
 2874505148349436413       2
 6182532736221468401       2
 3520220195726941342       2
-4570417408068703127       2
 5100927391589210255       2
-6910525070595717943       2
 1675441676719009369       2
-6914943110724904811       2
 8878665205966093747       1
-235437462833595589        1
-900886014368776044        1
 1971441525886001364       1
-8818942839839908252       1
 6915705793144674186       1
-8179330794391612308       1
 7859022659198800154       1
-5926937330317292544       1
-5067421808140477370       1
-9179793182211330025       1
-1928057671257924493       1
-3649125215608126215       1
 5216360749468983097       1
-5366919454465668251       1
-3045003044857910523       1
 7867329855710037182       1
 5797048120502934833       1
-1798957971582269170       1
-7698295521390300993       1
-1406954903166548856       1
-2924108161969870047       1
-2553121408496033070       1
 5232804510082391016       1
-554669136061361211        1
-4789212075489517532       1
 4158470747555640710       1
-7594203574664387476       1
-2033977572369517322       1
-6005396652975855097       1
-3720291673656662427       1
 7551380668308025354       1
-5405943280522698380       1
-7162226185021834384       1
 6953817646087564611       1
 6758189953370142489       1
-1132497911408226112       1
-781388289923283748        1
-3606290987821259708       1
-1887581614568949051       1
 6759623715801000040       1
-7641855192663099747       1
-3695620606866029050       1
-4934799694108021985       1
-2761461682691246918       1
-3824650187648628854       1
 2266313927732044767       1
-1396821880537214279       1
-5733931267564144309       1
-6930017410285140393       1
 7977422257641800688       1
 5380136689944095909       1
 7256379517037176713       1
-6968518901077158192       1
-5555660847397883917       1
-7195737547085680893       1
 5230000579752531602       1
-5236652920113302204       1
 8936803952615558670       1
 1595557920368290914       1
 2307316645084426942       1
-321552537169833793        1
-7518699381024305844       1
-2286768533275454563       1
 595640555568051652        1
-4754875637763106224       1
-4317138273541964845       1
 3635551857898739641       1
 7847619186796796084       1
 3196969023864641769       1
-3558486434361175644       1
-4526234991210405584       1
 1150786117133041713       1
 5763106017265139365       1
-599626584135603143        1
-2571905114943135262       1
 2890834138046221819       1
 138066566942838345        1
-7789439962211989994       1
 337495195680863518        1
-99077337081867836         1
-7557437905531322106       1
 9045063830272811070       1
-8425532349998861776       1
 6210961105960797620       1
-5118149969619127554       1
-2251923701993214355       1
-4236199745481231154       1
-8405285785047681224       1
 4112001970607120126       1
-3398248499422470718       1
-1274977674225985511       1
-2197761075471676610       1
 8854608033728029938       1
 4337564221051549528       1
 8607662765582828281       1
-4709701972300242869       1
 2242760664278873190       1
-1727227555222602005       1
 843125159274431080        1
-3360081611587712957       1
 3598662250356862282       1
 3400801791371040358       1
 4434427063325520328       1
-5375428840669828192       1
 5400509447230383444       1
 2768361175387329463       1
-2211681954486249140       1
-8630254554808469494       1
 2438846973070764815       1
-4816289482172287511       1
 2910328604019547969       1
-3906264335709000317       1
-2437306745591842461       1
 3532938866277543654       1
 3699106470332963671       1
-8992471532581037186       1
 6565558646477066273       1
-2286181384200332165       1
 4977973818027037764       1
 7832125428835646278       1
 4033348875742216178       1
-7459564348930826188       1
 3654276348050587796       1
-6500419880501473721       1
-8821774855349459387       1
 6036446504142460396       1
 5660551756125835187       1
 7919822482501145243       1
 1161578400968813655       1
-463155629190559529        1
-8692600660215247273       1
 5753024633661164610       1
 878534750241365141        1
 5363982839826799297       1
 1379408200929458307       1
-8700065760160479353       1
-5007099969679898744       1
-191806022797207155        1
 4977674121336782232       1
-6790000901983936116       1
 3741312134887255867       1
-7759074308363763111       1
-551332107213382088        1
 5625828905483550857       1
 8320653697101713532       1
-7082871253580838852       1
 3510944833163794547       1
 5954199008134408734       1
 7702894535030965711       1
-2840434167953522232       1
 5757318790945966234       1
 6641216749654759272       1
 7265819579832190598       1
-3438146584505839078       1
 3091750483610930896       1
 9047635618790672628       1
 4113327641666371223       1
-5062202179057722649       1
 8265642886370558071       1
 7158452277524287480       1
 8770419670485183201       1
 7908279193798077442       1
 8208698186419392546       1
 5137696554805514353       1
-5343184170725651083       1
-7091578704632084081       1
 3397452747792109772       1
 5312886250254371296       1
-7458302716833723          1
 727888284313957713        1
 5485890163360167357       1
 7392633132155011005       1
 2281754875268910080       1
 6311495451812094500       1
-2387874391172658434       1
 2035074766787807628       1
 8025914293814530709       1
-4370353509331099907       1
 8405270971821463343       1
-3868767358751119030       1
-3059333098905892413       1
 2840338015321199101       1
 2980955083832564140       1
 2669874023307133646       1
 6954899768925193714       1
 879439971758247327        1
-6680087784759370261       1
-3123328722007252436       1
 8401864105406790993       1
-8997856093426647374       1
-2287552604203635169       1
-4386790014251086061       1
-3348978172739825871       1
-7352615173975578505       1
-1659881508520575147       1
 802916410570306327        1
-7105351384026467590       1
-7544429878938196406       1
 933871365668580055        1
-5278458916885320132       1
-6242175980713174282       1
-6222351970473529790       1
-771121119115014020        1
-3260327890878341135       1
 1415050698063147539       1
 4432162052781673704       1
 3168658440946329969       1
 2612936360346328029       1
-6343149209980797253       1
-6956880848617158430       1
 8864120394134619640       1
-4036697752531026796       1
-1617707014325129775       1
-4956567493575679347       1
 5716197897720566318       1
-7828861912141690749       1
-1263341878135739419       1
-5122279124039554500       1
 7681037999772425652       1
 2524758391749152390       1
-3879869456458021624       1
 706166510299238548        1
-8467710475698539836       1
 1584364520008450096       1
 8556427726164600221       1
 7891496668349884643       1
 2676391676140974195       1
 3310947357689743516       1
 4011641048433061148       1
-6832656599657603367       1
 8962679560113522566       1
 2548810135973134041       1
-1986256106615932655       1
Name: Merchant Name, dtype: int64